### ISSUE TITLE
Refuses to connect, just "connecting" forever

### ISSUE THREAD

**Issue by AdrianTP** [magne4000/quassel-webserver#108]
Here's my `settings_user.js` file:
```js
module.exports = {
    default: {
        host: '<quassel server ip address>',
        port: 4242,
        initialBacklogLimit: 20,
        backlogLimit: 100
    },
    forcedefault: false,
    prefixpath: '/quassel',
    unsecurecore: false,
    theme: 'default'
};
```

Here's my Nginx config:
```nginx
server {
    listen 0.0.0.0:80;

    server_name <web server hostname> <web server ip address>;

    # rewrite ^[/]quassel$ /quassel/ permanent;
    location /quassel {
        proxy_pass http://127.0.0.1:64080/quassel;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_http_version 1.1;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location / {
      root /var/www/<root site name>/public_html;
      index index.html index.htm;
    }
}
```

I'm running this on Debian 7 with the following software versions:

```sh
root@Node1:/var/www/quassel-webserver# nginx -v
nginx version: nginx/1.6.2
root@Node1:/var/www/quassel-webserver# node -v
v0.12.9
```

It also happens running locally on my Mac running the same version of Node and accessing it directly at `http://127.0.0.1:64080` with nearly identical terminal output.

In order to get `quassel-webserver` to run as http on port 64080 I had to initialise it with `node app.js --mode http --port 64080`.

When I visit `http://<web server hostname>/quassel`, I am greeted by the Quassel Web App landing page. I enter my login credentials for my Quassel server and hit the Connect button, at which point the UI switches to the "Connecting" screen with the neverending loading bar animation and the terminal output on my server looks like this:

Relevant bit:
```sh
Connected to <quassel server ip address>:4242 (cdf7590477608b474650121f35d8d6059d4123338df309de589c92f5e7680902)
POST /quassel/p/connect 200 23.588 ms - 143
Forwarding socket with token cdf7590477608b474650121f35d8d6059d4123338df309de589c92f5e7680902
TCP connection closed by remote (cdf7590477608b474650121f35d8d6059d4123338df309de589c92f5e7680902)
Websocket connection closed (cdf7590477608b474650121f35d8d6059d4123338df309de589c92f5e7680902)
```

Full terminal output:
```sh
root@Node1:/var/www/quassel-webserver# node app.js --mode http --port 64080
GET /quassel/ 200 1186.522 ms - 14397
GET /quassel/stylesheets/bootstrap.min.css 200 7.585 ms - 118036
GET /quassel/stylesheets/fonts.css 200 3.014 ms - 1818
GET /quassel/javascripts/angular-aria.min.js 200 97.123 ms - 3773
GET /quassel/javascripts/jquery-2.1.3.min.js 200 96.922 ms - 84320
GET /quassel/javascripts/angular.min.js 200 97.104 ms - 148198
GET /quassel/javascripts/bootstrap-tokenfield.min.js 200 9.411 ms - 17505
GET /quassel/javascripts/ui-bootstrap-tpls-0.12.0.min.js 200 9.340 ms - 65175
GET /quassel/javascripts/favico-0.3.10.min.js 200 4.486 ms - 9033
GET /quassel/javascripts/ng-quassel.js 200 4.388 ms - 6337
GET /quassel/stylesheets/theme-default.css 200 346.438 ms - 16880
GET /quassel/javascripts/angular-sanitize.js 200 1.998 ms - 24922
GET /quassel/javascripts/angular-dnd.min.js 200 1.153 ms - 2786
GET /quassel/javascripts/angular-notify.min.js 200 0.529 ms - 2820
GET /quassel/javascripts/libquassel.js 200 3.013 ms - 879672
GET /quassel/javascripts/angular-init.js 200 1.277 ms - 5535
GET /quassel/javascripts/angular-directive.js 200 1.084 ms - 18307
GET /quassel/javascripts/angular-filter.js 200 1.042 ms - 7692
GET /quassel/javascripts/angular-controller.js 200 3.203 ms - 26784
GET /quassel/stylesheets/fonts/Roboto-Light-webfont.woff 200 1.407 ms - 105544
GET /quassel/fonts/glyphicons-halflings-regular.woff2 200 1.806 ms - 18028
GET /quassel/stylesheets/fonts/RobotoCondensed-Regular-webfont.woff 200 1.071 ms - 109020
GET /quassel/stylesheets/fonts/DroidSansMono-webfont.woff 200 2.464 ms - 11744
GET /quassel/stylesheets/fonts/Roboto-Regular-webfont.woff 200 1.534 ms - 105700
GET /quassel/javascripts/angular.min.js.map 404 12.713 ms - 1044
Error: Not Found
    at /var/www/quassel-webserver/app.js:123:15
    at Layer.handle [as handle_request] (/var/www/quassel-webserver/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/quassel-webserver/node_modules/express/lib/router/index.js:312:13)
    at /var/www/quassel-webserver/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/var/www/quassel-webserver/node_modules/express/lib/router/index.js:330:12)
    at next (/var/www/quassel-webserver/node_modules/express/lib/router/index.js:271:10)
    at /var/www/quassel-webserver/node_modules/express/lib/router/index.js:618:15
    at next (/var/www/quassel-webserver/node_modules/express/lib/router/index.js:256:14)
    at Function.handle (/var/www/quassel-webserver/node_modules/express/lib/router/index.js:176:3)
    at router (/var/www/quassel-webserver/node_modules/express/lib/router/index.js:46:12)
GET /quassel/javascripts/angular-aria.min.js.map 404 3.838 ms - 1044
Error: Not Found
    at /var/www/quassel-webserver/app.js:123:15
    at Layer.handle [as handle_request] (/var/www/quassel-webserver/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/quassel-webserver/node_modules/express/lib/router/index.js:312:13)
    at /var/www/quassel-webserver/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/var/www/quassel-webserver/node_modules/express/lib/router/index.js:330:12)
    at next (/var/www/quassel-webserver/node_modules/express/lib/router/index.js:271:10)
    at /var/www/quassel-webserver/node_modules/express/lib/router/index.js:618:15
    at next (/var/www/quassel-webserver/node_modules/express/lib/router/index.js:256:14)
    at Function.handle (/var/www/quassel-webserver/node_modules/express/lib/router/index.js:176:3)
    at router (/var/www/quassel-webserver/node_modules/express/lib/router/index.js:46:12)
GET /quassel/javascripts/angular-dnd.min.js.map 404 2.180 ms - 1044
Error: Not Found
    at /var/www/quassel-webserver/app.js:123:15
    at Layer.handle [as handle_request] (/var/www/quassel-webserver/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/quassel-webserver/node_modules/express/lib/router/index.js:312:13)
    at /var/www/quassel-webserver/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/var/www/quassel-webserver/node_modules/express/lib/router/index.js:330:12)
    at next (/var/www/quassel-webserver/node_modules/express/lib/router/index.js:271:10)
    at /var/www/quassel-webserver/node_modules/express/lib/router/index.js:618:15
    at next (/var/www/quassel-webserver/node_modules/express/lib/router/index.js:256:14)
    at Function.handle (/var/www/quassel-webserver/node_modules/express/lib/router/index.js:176:3)
    at router (/var/www/quassel-webserver/node_modules/express/lib/router/index.js:46:12)
GET /quassel/images/hide-pane-left.png 200 5.686 ms - 271
GET /quassel/images/hide-pane-right.png 200 0.644 ms - 262
GET /quassel/images/quassel-logo.png 200 1.535 ms - 511
GET /quassel/favicon.ico 200 5.907 ms - 32988
GET /quassel/stylesheets/theme-darksolarized.css 200 193.943 ms - 18217
Connected to 162.243.110.48:4242 (cdf7590477608b474650121f35d8d6059d4123338df309de589c92f5e7680902)
POST /quassel/p/connect 200 23.588 ms - 143
Forwarding socket with token cdf7590477608b474650121f35d8d6059d4123338df309de589c92f5e7680902
TCP connection closed by remote (cdf7590477608b474650121f35d8d6059d4123338df309de589c92f5e7680902)
Websocket connection closed (cdf7590477608b474650121f35d8d6059d4123338df309de589c92f5e7680902)
^@^@^@^@
```

Please send help. I've been banging my head against the wall for hours trying workarounds and have yet to achieve success.

**Comment by magne4000** [comment]
Can you try removing your `node_modules` folder and then run `npm install` ?

**Comment by magne4000** [comment]
Also, what is your core version ?

**Comment by magne4000** [comment]
Closing this since I have no feedback
