### ISSUE TITLE
Scripting error on chrome

### ISSUE THREAD

**Issue by tecknojock** [magne4000/quassel-webserver#136]
It works on firefox and ie, but I dont know what's going on w/ chrome. Wont even make the login page:

SyntaxError: Unexpected token g
    at Object.parse (native)
    at Object.get (https://gyro.tech:64443/javascripts/angular-init.js:96:40)
    at new <anonymous> (https://gyro.tech:64443/javascripts/angular-controller.js:479:45)
    at Object.invoke (https://gyro.tech:64443/javascripts/angular.min.js:41:295)
    at T.instance (https://gyro.tech:64443/javascripts/angular.min.js:86:444)
    at u (https://gyro.tech:64443/javascripts/angular.min.js:65:338)
    at g (https://gyro.tech:64443/javascripts/angular.min.js:58:136)
    at g (https://gyro.tech:64443/javascripts/angular.min.js:58:153)
    at u (https://gyro.tech:64443/javascripts/angular.min.js:66:270)
    at g (https://gyro.tech:64443/javascripts/angular.min.js:58:136)(anonymous function) @ angular.min.js:114

This started just recently. I've disabled all my plugins for testing. I dont see any errors on the server. I thought it might be filtering initially, but as I said, IE and firefox handle it just fine, so it shouldn't be my work filtering it.

**Comment by magne4000** [comment]
The configuration in your Javascript `localStorage` object has been messed up by some incoherence in the way I used `host` and `port` values.
This fix should delete those wrong values.
