### ISSUE TITLE
Bug: TLSSocket issue

### ISSUE THREAD

**Issue by eparon** [magne4000/quassel-webserver#166]
I encountered a new issue and the following error was logged:
```
/home/user/quassel-webserver/node_modules/ws/lib/Receiver.js:386
    default: srcBuffer.copy(dstBuffer, dstOffset, 0, length); break;
                       ^

RangeError: out of range index
    at RangeError (native)
    at fastCopy (/home/user/quassel-webserver/node_modules/ws/lib/Receiver.js:386:24)
    at Receiver.add (/home/user/quassel-webserver/node_modules/ws/lib/Receiver.js:86:3)
    at TLSSocket.realHandler (/home/user/quassel-webserver/node_modules/ws/lib/WebSocket.js:800:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at TLSSocket.Readable.push (_stream_readable.js:135:10)
    at TLSWrap.onread (net.js:542:20)
```
node.js version: 6.3.0
quassel-core version: 0.12.4

**Comment by magne4000** [comment]
https://github.com/websockets/ws/issues/778

**Comment by magne4000** [comment]
`npm update` and you should be good
