### ISSUE TITLE
Bug: TLS Socket error

### ISSUE THREAD

**Issue by eparon** [magne4000/quassel-webserver#171]
This issue might be related with #166 .

The error I get is the following:
```
home/user/quassel-webserver/node_modules/ws/lib/Receiver.js:386
    default: srcBuffer.copy(dstBuffer, dstOffset, 0, length); break;
                       ^

RangeError: out of range index
    at RangeError (native)
    at fastCopy (/home/user/quassel-webserver/node_modules/ws/lib/Receiver.js:38
6:24)
    at Receiver.add (/home/user/quassel-webserver/node_modules/ws/lib/Receiver.j
s:86:3)
    at TLSSocket.realHandler (/home/user/quassel-webserver/node_modules/ws/lib/W
ebSocket.js:800:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at TLSSocket.Readable.push (_stream_readable.js:135:10)
    at TLSWrap.onread (net.js:542:20)
```
-------------------
node.js version: 6.3.0
quassel core: 0.12.4
quassel-webserver commit: b17fe74

**Comment by magne4000** [comment]
It's exactly the same issue, `npm update` fixes the issue

**Comment by magne4000** [comment]
If this doesn't fix the issue, please tell me what have changed since last time.

**Comment by magne4000** [comment]
Also, launch a `git pull` before `npm install` (or just `npm update` afterward). I changed a dependency version that could have cause the issue not to be fixed.

**Comment by eparon** [comment]
no strange behavior so far, so i'm closing the issue!
