### ISSUE TITLE
snap installation fails: "TypeError: this is not a typed array."

### ISSUE THREAD

**Issue by louwers** [magne4000/quassel-webserver#250]
I installed quassel-webserver using snap. However, it fails to start and I found this in my logs:

```
Oct 11 23:30:20 scw-902385 snap[6017]: /var/lib/snapd/snap/quassel-webserver/23/lib/node_modules/quassel-webserver/node_modules/net-browserify-alt/node_module
Oct 11 23:30:20 scw-902385 snap[6017]: const TRAILER = Buffer.from([0x00, 0x00, 0xff, 0xff]);
Oct 11 23:30:20 scw-902385 snap[6017]:                        ^
Oct 11 23:30:20 scw-902385 snap[6017]: TypeError: this is not a typed array.
Oct 11 23:30:20 scw-902385 snap[6017]:     at Function.from (native)
Oct 11 23:30:20 scw-902385 snap[6017]:     at Object.<anonymous> (/var/lib/snapd/snap/quassel-webserver/23/lib/node_modules/quassel-webserver/node_modules/net
Oct 11 23:30:20 scw-902385 snap[6017]:     at Module._compile (module.js:409:26)
Oct 11 23:30:20 scw-902385 snap[6017]:     at Object.Module._extensions..js (module.js:416:10)
Oct 11 23:30:20 scw-902385 snap[6017]:     at Module.load (module.js:343:32)
Oct 11 23:30:20 scw-902385 snap[6017]:     at Function.Module._load (module.js:300:12)
Oct 11 23:30:20 scw-902385 snap[6017]:     at Module.require (module.js:353:17)
Oct 11 23:30:20 scw-902385 snap[6017]:     at require (internal/module.js:12:17)
Oct 11 23:30:20 scw-902385 snap[6017]:     at Object.<anonymous> (/var/lib/snapd/snap/quassel-webserver/23/lib/node_modules/quassel-webserver/node_modules/net
Oct 11 23:30:20 scw-902385 snap[6017]:     at Module._compile (module.js:409:26)
Oct 11 23:30:20 scw-902385 systemd[1]: snap.quassel-webserver.server.service: Main process exited, code=exited, status=1/FAILURE
Oct 11 23:30:20 scw-902385 systemd[1]: snap.quassel-webserver.server.service: Failed with result 'exit-code'.
Oct 11 23:30:20 scw-902385 systemd[1]: snap.quassel-webserver.server.service: Service hold-off time over, scheduling restart.
Oct 11 23:30:20 scw-902385 systemd[1]: snap.quassel-webserver.server.service: Scheduled restart job, restart counter is at 5.
```

**Comment by magne4000** [comment]
You certainly are using an old version of node here, as `Buffer.from` was introduced in node 6.0.0

**Comment by louwers** [comment]
I am running v8.6.0 on my machine. But I guess that doesn't matter because snap uses it's own node version? Using snapd 2.26.1-2 if it matters.
