### ISSUE TITLE
Support for nodejs 11+

### ISSUE THREAD

**Issue by gschanuel** [magne4000/quassel-webserver#278]
I'm running nodejs 11.15.0-1 on archlinux. ws@7.0.1
When I try to start quassel-webserver I get

```
Jun 22 02:07:42 vostro systemd[1]: Started quassel-webserver.service.
Jun 22 02:07:42 vostro quassel-webserver[26885]: internal/modules/cjs/loader.js:670
Jun 22 02:07:42 vostro quassel-webserver[26885]:     throw err;
Jun 22 02:07:42 vostro quassel-webserver[26885]:     ^
Jun 22 02:07:42 vostro quassel-webserver[26885]: Error: Cannot find module './ws'
Jun 22 02:07:42 vostro quassel-webserver[26885]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
Jun 22 02:07:42 vostro quassel-webserver[26885]:     at Function.Module._load (internal/modules/cjs/loader.js:591:27)
Jun 22 02:07:42 vostro quassel-webserver[26885]:     at Module.require (internal/modules/cjs/loader.js:723:19)
Jun 22 02:07:42 vostro quassel-webserver[26885]:     at require (internal/modules/cjs/helpers.js:14:16)
Jun 22 02:07:42 vostro quassel-webserver[26885]:     at Object.<anonymous> (/usr/share/webapps/quassel-webserver/app.js:13:10)
Jun 22 02:07:42 vostro quassel-webserver[26885]:     at Module._compile (internal/modules/cjs/loader.js:816:30)
Jun 22 02:07:42 vostro quassel-webserver[26885]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
Jun 22 02:07:42 vostro quassel-webserver[26885]:     at Module.load (internal/modules/cjs/loader.js:685:32)
Jun 22 02:07:42 vostro quassel-webserver[26885]:     at Function.Module._load (internal/modules/cjs/loader.js:620:12)
Jun 22 02:07:42 vostro quassel-webserver[26885]:     at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Jun 22 02:07:42 vostro systemd[1]: quassel-webserver.service: Main process exited, code=exited, status=1/FAILURE
Jun 22 02:07:42 vostro systemd[1]: quassel-webserver.service: Failed with result 'exit-code'.
Jun 22 02:07:43 vostro systemd[1]: quassel-webserver.service: Service RestartSec=100ms expired, scheduling restart.
Jun 22 02:07:43 vostro systemd[1]: quassel-webserver.service: Scheduled restart job, restart counter is at 5.
Jun 22 02:07:43 vostro systemd[1]: Stopped quassel-webserver.service.
```

`

**Comment by ohnx** [comment]
Are you sure quassel-webserver was installed properly? Based on the error logs, it seems like the issue is that the local file `ws.js` isn't there or can't be found (maybe the working directory is wrong?). It seems strange that the other files do work, though.

The program works fine for me with nodes 11.15.0 on Debian with a fresh git clone and `npm install`, so I'm not sure what to say other than to possibly try reinstalling. Good luck!

**Comment by digitalcircuit** [comment]
I successfully migrated from NodeJS v10 to v12 today with no issues so far, just [changing the repository URL](https://github.com/digitalcircuit/salt-box-quassel/commit/2090a48b7d3fcab722f892261ddb3ec84c074029 ) and upgrading the `nodejs` package.

My full Quassel Webserver (+ Quassel, Quassel Search, etc) setup can be found in [salt-box-quassel](https://github.com/digitalcircuit/salt-box-quassel ), in case that might be of help.
