### ISSUE TITLE
Crash on buffer.js

### ISSUE THREAD

**Issue by Lartza** [magne4000/quassel-webserver#35]
The app crashes after something, maybe too large buffer or something. It's not right after it starts, sometimes it doesn't crash for two hours and sometimes it crashes in 10 minutes.
```
    Error while fetching buffer size index out of range
    GET /quassel/images/icon-away.png 304 0.872 ms - -
    GET /quassel/ 304 492.038 ms - -
    GET /quassel/javascripts/jquery-2.1.3.min.js 304 3.400 ms - -
    GET /quassel/javascripts/angular.min.js 304 1.986 ms - -
    GET /quassel/stylesheets/fonts.css 304 6.681 ms - -
    GET /quassel/stylesheets/bootstrap.min.css 304 1.042 ms - -
    GET /quassel/stylesheets/theme-default.css 304 1.511 ms - -
    GET /quassel/javascripts/ui-bootstrap-tpls-0.12.0.min.js 304 1.231 ms - -
    GET /quassel/javascripts/favico-0.3.6.min.js 304 1.877 ms - -
    GET /quassel/javascripts/ngSocket.js 304 1.329 ms - -
    GET /quassel/javascripts/events.js 304 1.735 ms - -
    GET /quassel/javascripts/angular-sanitize.min.js 304 1.462 ms - -
    GET /quassel/javascripts/angular-dnd.min.js 304 0.497 ms - -
    GET /quassel/javascripts/angular-notify.min.js 304 1.126 ms - -
    GET /quassel/javascripts/json-patch.js 304 3.479 ms - -
    GET /quassel/javascripts/libquassel.js 304 3.242 ms - -
    GET /quassel/javascripts/angular-init.js 304 1.058 ms - -
    GET /quassel/javascripts/angular-directive.js 304 0.779 ms - -
    GET /quassel/javascripts/angular-filter.js 304 0.956 ms - -
    GET /quassel/javascripts/angular-controller.js 304 0.777 ms - -
    GET /quassel/images/quassel-logo.png 304 4.909 ms - -
    GET /quassel/fonts/glyphicons-halflings-regular.woff2 304 4.128 ms - -
    GET /quassel/stylesheets/fonts/Roboto-Light-webfont.woff 304 3.721 ms - -
    GET /quassel/stylesheets/fonts/Roboto-Regular-webfont.woff 304 4.881 ms - -
    GET /quassel/favicon.ico 304 0.867 ms - -
    GET /quassel/images/hide-pane-left.png 304 3.216 ms - -
    GET /quassel/images/hide-pane-right.png 304 2.320 ms - -
    GET /quassel/stylesheets/fonts/RobotoCondensed-Regular-webfont.woff 304 7.800 ms - -
    GET /quassel/stylesheets/fonts/DroidSansMono-webfont.woff 304 3.174 ms - -
    GET /quassel/images/icon-away.png 304 1.563 ms - -
    GET /quassel/images/icon-active.png 304 1.102 ms - -
    GET /quassel/ 200 256.440 ms - 9382
    GET /quassel/stylesheets/fonts.css 200 21.942 ms - 1818
    GET /quassel/stylesheets/theme-default.css 200 29.564 ms - 11583
    GET /quassel/javascripts/ui-bootstrap-tpls-0.12.0.min.js 200 21.122 ms - 65175
    GET /quassel/stylesheets/bootstrap.min.css 200 31.765 ms - 118036
    GET /quassel/javascripts/angular.min.js 200 24.089 ms - 125499
    GET /quassel/javascripts/jquery-2.1.3.min.js 200 32.617 ms - 84320
    GET /quassel/javascripts/favico-0.3.6.min.js 200 10.279 ms - 9014
    GET /quassel/javascripts/ngSocket.js 200 1.714 ms - 2757
    GET /quassel/javascripts/events.js 200 16.796 ms - 7858
    GET /quassel/javascripts/angular-notify.min.js 200 1.904 ms - 2820
    GET /quassel/javascripts/angular-sanitize.min.js 200 22.507 ms - 6140
    GET /quassel/javascripts/angular-dnd.min.js 200 29.845 ms - 2786
    GET /quassel/javascripts/libquassel.js 200 15.728 ms - 57284
    GET /quassel/javascripts/json-patch.js 200 5.257 ms - 14272
    GET /quassel/javascripts/angular-init.js 200 23.255 ms - 4631
    GET /quassel/javascripts/angular-directive.js 200 3.216 ms - 11552
    GET /quassel/javascripts/angular-filter.js 200 2.214 ms - 9588
    GET /quassel/javascripts/angular-controller.js 200 4.946 ms - 19882
    GET /quassel/fonts/glyphicons-halflings-regular.woff2 200 1.259 ms - 18028
    GET /quassel/images/quassel-logo.png 200 1.029 ms - 511
    GET /quassel/stylesheets/fonts/Roboto-Light-webfont.woff 200 33.827 ms - 105544
    GET /quassel/stylesheets/fonts/Roboto-Regular-webfont.woff 200 16.221 ms - 105700
    GET /quassel/favicon.ico 200 1.994 ms - 32988
    GET /quassel/images/hide-pane-right.png 200 18.913 ms - 262
    GET /quassel/images/hide-pane-left.png 200 32.449 ms - 271
    GET /quassel/stylesheets/fonts/RobotoCondensed-Regular-webfont.woff 200 31.729 ms - 109020
    GET /quassel/stylesheets/fonts/DroidSansMono-webfont.woff 200 25.414 ms - 11744
    GET /quassel/images/icon-active.png 200 10.852 ms - 301
    GET /quassel/images/icon-away.png 200 10.096 ms - 285
    /home/lartza/quassel-webserver/node_modules/libquassel/lib/buffer.js:60
        this.nickUserMap[user.nick] = user;
                             ^
    TypeError: Cannot read property 'nick' of null
        at IRCBuffer.addUser (/home/lartza/quassel-webserver/node_modules/libquassel/lib/buffer.js:60:26)
        at handleStruct (/home/lartza/quassel-webserver/node_modules/libquassel/lib/libquassel.js:458:44)
        at dispatch (/home/lartza/quassel-webserver/node_modules/libquassel/lib/libquassel.js:135:13)
        at Socket.<anonymous> (/home/lartza/quassel-webserver/node_modules/libquassel/lib/libquassel.js:109:13)
        at Socket.emit (events.js:107:17)
        at handleData (/home/lartza/quassel-webserver/node_modules/libquassel/node_modules/qtdatastream/lib/qtdatastream.js:145:26)
        at TLSSocket.<anonymous> (/home/lartza/quassel-webserver/node_modules/libquassel/node_modules/qtdatastream/lib/qtdatastream.js:114:13)
        at TLSSocket.emit (events.js:107:17)
        at readableAddChunk (_stream_readable.js:163:16)
        at TLSSocket.Readable.push (_stream_readable.js:126:10)
        at TCP.onread (net.js:529:20)
```

There were more buffer index out of range errors earlier too. This happened before the commits yesterday too, not a regression.

Running on Ubuntu 14.04.2 and Node v0.12.0

**Comment by Zren** [comment]
Also:

```
c:\Users\Admin\Desktop\quassel-webserver\node_modules\libquassel\lib\buffer.js:70
    this.nickUserModesMap[user.nick] += mode;
                              ^
TypeError: Cannot read property 'nick' of null
    at IRCBuffer.addUserMode (c:\Users\Admin\Desktop\quassel-webserver\node_modules\libquassel\lib\buffer.js:70:31)
    at handleStruct (c:\Users\Admin\Desktop\quassel-webserver\node_modules\libquassel\lib\libquassel.js:466:40)
    at dispatch (c:\Users\Admin\Desktop\quassel-webserver\node_modules\libquassel\lib\libquassel.js:135:13)
    at Socket.<anonymous> (c:\Users\Admin\Desktop\quassel-webserver\node_modules\libquassel\lib\libquassel.js:109:13)
    at emitOne (events.js:75:13)
    at Socket.emit (events.js:150:7)
    at handleData (c:\Users\Admin\Desktop\quassel-webserver\node_modules\libquassel\node_modules\qtdatastream\lib\qtdatastream.js:145:26)
    at TLSSocket.<anonymous> (c:\Users\Admin\Desktop\quassel-webserver\node_modules\libquassel\node_modules\qtdatastream\lib\qtdatastream.js:114:13)
    at emitOne (events.js:75:13)
    at TLSSocket.emit (events.js:150:7)
```

**Comment by magne4000** [comment]
@Lartza do not hesitate to reopen the issue if you still have the same problem, as I'm unable to reproduce it (you just need ```npm update``` to apply the fix)
