### ISSUE TITLE
Not working in IE11

### ISSUE THREAD

**Issue by willrea** [magne4000/quassel-webserver#55]
I get the following in the error console on a current checkout:

```
HTML1407: Invalid tag name. First character should match [a-zA-Z].
File: keekers.org:64443, Line: 1, Column: 10054

AngularJS loaded
CONNECTED
Logged in

TypeError: Unable to get property 'prototype' of undefined or null reference
   at Reviver.prototype.revive (https://keekers.org:64443/javascripts/libquassel.js:2441:9)
   at Reviver.prototype.reviveAll (https://keekers.org:64443/javascripts/libquassel.js:2451:5)
   at Anonymous function (https://keekers.org:64443/javascripts/angular-controller.js:97:13)
   at l.prototype.$eval (https://keekers.org:64443/javascripts/angular.min.js:125:294)
   at l.prototype.$apply (https://keekers.org:64443/javascripts/angular.min.js:125:507)
   at Anonymous function (https://keekers.org:64443/javascripts/angular-controller.js:95:9)
   at ConditionedEventReceiver.prototype._call (https://keekers.org:64443/javascripts/events.js:100:13)
   at Anonymous function (https://keekers.org:64443/javascripts/events.js:172:21)
   at Anonymous function (https://keekers.org:64443/javascripts/ngSocket.js:72:15)
   at Emitter.prototype.emit (https://keekers.org:64443/socket.io/socket.io.js:1335:7)
   
   SCRIPT5007: Unable to get property 'prototype' of undefined or null reference
File: libquassel.js, Line: 2441, Column: 9
```

**Comment by magne4000** [comment]
What is your NodeJS Version ? Browser ?

**Comment by willrea** [comment]
Using NodeJS version 0.12.3

**Comment by Zren** [comment]
Found the bug.

The reviver classes are being pushed with a key of undefined since IE doesn't have the `function.name` property.

![](http://i.imgur.com/NokISfS.png)

**Comment by magne4000** [comment]
Meh. Thanks IE :expressionless:

**Comment by magne4000** [comment]
And thank you @Zren for the analysis ;)
