### ISSUE TITLE
Error: Cannot find module 'options'

### ISSUE THREAD

**Issue by edrex** [magne4000/quassel-webserver#73]
```
% git pull
5048995..4b22957
% npm update --production
% node app.js
module.js:338
    throw err;
          ^
Error: Cannot find module 'options'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/eric/Code/quassel-webserver/node_modules/net-browserify/node_modules/express-ws/node_modules/ws/lib/WebSocket.js:14:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

`git bisect` shows that 4480a3de9d introduces the error.

**Comment by magne4000** [comment]
hum weird, probably a npm bug, because `options` is listed as a ws dependency : https://github.com/websockets/ws/blob/master/package.json

**Comment by edrex** [comment]
Right, deleting `node_modules` and reinstalling fixed it.
