### ISSUE TITLE
404 with nginx reverse proxy

### ISSUE THREAD

**Issue by sdfg2** [magne4000/quassel-webserver#92]
I've copy and pasted the nginx reverse proxy snippet, but whenever I access the page I get the following:
```
Not Found
404

Error: Not Found
    at /var/lib/quassel-webserver/app.js:123:15
    at Layer.handle [as handle_request] (/var/lib/quassel-webserver/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/lib/quassel-webserver/node_modules/express/lib/router/index.js:312:13)
    at /var/lib/quassel-webserver/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/var/lib/quassel-webserver/node_modules/express/lib/router/index.js:330:12)
    at next (/var/lib/quassel-webserver/node_modules/express/lib/router/index.js:271:10)
    at /var/lib/quassel-webserver/node_modules/express/lib/router/index.js:618:15
    at next (/var/lib/quassel-webserver/node_modules/express/lib/router/index.js:256:14)
    at Function.handle (/var/lib/quassel-webserver/node_modules/express/lib/router/index.js:176:3)
    at router (/var/lib/quassel-webserver/node_modules/express/lib/router/index.js:46:12)
```

**Comment by magne4000** [comment]
You probably need to set `prefixpath: '/quassel',` in your `settings-user.js` file
